name: corretor_desktop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  image: ^4.6.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdfrx: ^2.1.5
  sizer: ^3.1.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  tflite_flutter: ^0.12.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/python/
    - assets/models/
    - assets/images/
    - assets/vectors/
